Repository AndLetgo/2nd-Main-JeonsiLog-Server, pull requests merged in 2023-12, with the labels that each got.

#7 ✨ [FEAT]: 시큐리티 템플릿 적용, Auth API 개발
  .gitignore
  build.gradle
  src/main/java/depth/jeonsilog/JeonsiLogServerApplication.java
  src/main/java/depth/jeonsilog/domain/auth/application/AuthService.java
  src/main/java/depth/jeonsilog/domain/auth/application/CustomTokenProviderService.java
  src/main/java/depth/jeonsilog/domain/auth/application/CustomUserDetailsService.java
  src/main/java/depth/jeonsilog/domain/auth/converter/AuthConverter.java
  src/main/java/depth/jeonsilog/domain/auth/domain/repository/CustomAuthorizationRequestRepository.java
  src/main/java/depth/jeonsilog/domain/auth/domain/repository/TokenRepository.java
  src/main/java/depth/jeonsilog/domain/auth/dto/AuthRequestDto.java
  src/main/java/depth/jeonsilog/domain/auth/dto/AuthResponseDto.java
  src/main/java/depth/jeonsilog/domain/auth/dto/TokenMapping.java
  src/main/java/depth/jeonsilog/domain/auth/presentation/AuthController.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
  src/main/java/depth/jeonsilog/domain/user/domain/Provider.java
  src/main/java/depth/jeonsilog/domain/user/domain/Role.java
  src/main/java/depth/jeonsilog/domain/user/domain/User.java
  src/main/java/depth/jeonsilog/domain/user/domain/repository/UserRepository.java
  src/main/java/depth/jeonsilog/global/DefaultAssert.java
  src/main/java/depth/jeonsilog/global/config/JpaConfig.java
  src/main/java/depth/jeonsilog/global/config/TomcatWebCustomConfig.java
  src/main/java/depth/jeonsilog/global/config/security/OAuth2Config.java
  src/main/java/depth/jeonsilog/global/config/security/SecurityConfig.java
  src/main/java/depth/jeonsilog/global/config/security/handler/CustomSimpleUrlAuthenticationFailureHandler.java
  src/main/java/depth/jeonsilog/global/config/security/handler/CustomSimpleUrlAuthenticationSuccessHandler.java
  src/main/java/depth/jeonsilog/global/config/security/token/CurrentUser.java
  src/main/java/depth/jeonsilog/global/config/security/token/CustomAuthenticationEntryPoint.java
  src/main/java/depth/jeonsilog/global/config/security/token/CustomOncePerRequestFilter.java
  src/main/java/depth/jeonsilog/global/config/security/token/UserPrincipal.java
  src/main/java/depth/jeonsilog/global/config/security/util/CustomCookie.java
  src/main/java/depth/jeonsilog/global/error/ApiControllerAdvice.java
  src/main/java/depth/jeonsilog/global/error/DefaultAuthenticationException.java
  src/main/java/depth/jeonsilog/global/error/DefaultException.java
  src/main/java/depth/jeonsilog/global/error/DefaultNullPointerException.java
  src/main/java/depth/jeonsilog/global/error/InvalidParameterException.java
  src/main/java/depth/jeonsilog/global/payload/ApiResponse.java
  src/main/java/depth/jeonsilog/global/payload/ErrorCode.java
  src/main/java/depth/jeonsilog/global/payload/ErrorResponse.java
  src/main/java/depth/jeonsilog/global/payload/Message.java
  src/main/resources/application.yml
Labels: enhancement

#13 ✨ [FEAT]: User API 개발
  src/main/java/depth/jeonsilog/domain/auth/application/AuthService.java
  src/main/java/depth/jeonsilog/domain/auth/dto/AuthRequestDto.java
  src/main/java/depth/jeonsilog/domain/auth/dto/AuthResponseDto.java
  src/main/java/depth/jeonsilog/domain/auth/presentation/AuthController.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
  src/main/java/depth/jeonsilog/domain/rating/domain/Rating.java
  src/main/java/depth/jeonsilog/domain/review/domain/Review.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
  src/main/java/depth/jeonsilog/domain/user/domain/User.java
  src/main/java/depth/jeonsilog/domain/user/domain/repository/UserRepository.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserRequestDto.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
  src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
  src/main/java/depth/jeonsilog/global/config/security/SecurityConfig.java
Labels: :sparkles: feature

#17 🚀 [FEAT]: 3차 배포
  src/main/java/depth/jeonsilog/domain/auth/application/AuthService.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
  src/main/java/depth/jeonsilog/domain/follow/application/FollowService.java
  src/main/java/depth/jeonsilog/domain/follow/converter/FollowConverter.java
  src/main/java/depth/jeonsilog/domain/follow/domain/repository/FollowRepository.java
  src/main/java/depth/jeonsilog/domain/follow/dto/FollowResponseDto.java
  src/main/java/depth/jeonsilog/domain/follow/presentation/FollowController.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
  src/main/java/depth/jeonsilog/domain/user/domain/repository/UserRepository.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
  src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
  src/main/java/depth/jeonsilog/global/payload/ApiResponse.java
Labels: :rocket: deployment

#22 ✨ [FEAT]: 즐겨찾기, 별점, 감상평 API 개발
  src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
  src/main/java/depth/jeonsilog/domain/interest/application/InterestService.java
  src/main/java/depth/jeonsilog/domain/interest/converter/InterestConverter.java
  src/main/java/depth/jeonsilog/domain/interest/domain/repository/InterestRepository.java
  src/main/java/depth/jeonsilog/domain/interest/dto/InterestResponseDto.java
  src/main/java/depth/jeonsilog/domain/interest/presentation/InterestController.java
  src/main/java/depth/jeonsilog/domain/place/domain/repository/PlaceRepository.java
  src/main/java/depth/jeonsilog/domain/rating/application/RatingService.java
  src/main/java/depth/jeonsilog/domain/rating/converter/RatingConverter.java
  src/main/java/depth/jeonsilog/domain/rating/domain/Rating.java
  src/main/java/depth/jeonsilog/domain/rating/domain/repository/RatingRepository.java
  src/main/java/depth/jeonsilog/domain/rating/dto/RatingRequestDto.java
  src/main/java/depth/jeonsilog/domain/rating/dto/RatingResponseDto.java
  src/main/java/depth/jeonsilog/domain/rating/presentation/RatingController.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
  src/main/java/depth/jeonsilog/domain/review/domain/Review.java
  src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewRequestDto.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
  src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
Labels: :sparkles: feature

#24 ✨ [FEAT]: 전시회, 전시 공간 API 개발
  .github/PR_TEMPLATE/pull_request_template.md
  build.gradle
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/exhibition/converter/ExhibitionConverter.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/OperatingKeyword.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
  src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionRequestDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionResponseDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
  src/main/java/depth/jeonsilog/domain/image/domain/Image.java
  src/main/java/depth/jeonsilog/domain/openApi/application/SaveService.java
  src/main/java/depth/jeonsilog/domain/openApi/dto/API/ExhibitionDetailDTO.java
  src/main/java/depth/jeonsilog/domain/openApi/dto/API/ExhibitionListDTO.java
  src/main/java/depth/jeonsilog/domain/openApi/dto/API/PlaceDetailDTO.java
  src/main/java/depth/jeonsilog/domain/openApi/presentation/SaveController.java
  src/main/java/depth/jeonsilog/domain/place/application/PlaceService.java
  src/main/java/depth/jeonsilog/domain/place/converter/PlaceConverter.java
  src/main/java/depth/jeonsilog/domain/place/domain/Place.java
  src/main/java/depth/jeonsilog/domain/place/domain/repository/PlaceRepository.java
  src/main/java/depth/jeonsilog/domain/place/dto/PlaceRequestDto.java
  src/main/java/depth/jeonsilog/domain/place/dto/PlaceResponseDto.java
  src/main/java/depth/jeonsilog/domain/place/presentation/PlaceController.java
Labels: :sparkles: feature

#25 🚀 [FEAT]: 4차 배포
  build.gradle
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/exhibition/converter/ExhibitionConverter.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/OperatingKeyword.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
  src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionRequestDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionResponseDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
  src/main/java/depth/jeonsilog/domain/image/domain/Image.java
  src/main/java/depth/jeonsilog/domain/interest/application/InterestService.java
  src/main/java/depth/jeonsilog/domain/interest/converter/InterestConverter.java
  src/main/java/depth/jeonsilog/domain/interest/domain/repository/InterestRepository.java
  src/main/java/depth/jeonsilog/domain/interest/dto/InterestResponseDto.java
  src/main/java/depth/jeonsilog/domain/interest/presentation/InterestController.java
  src/main/java/depth/jeonsilog/domain/openApi/application/SaveService.java
  src/main/java/depth/jeonsilog/domain/openApi/dto/API/ExhibitionDetailDTO.java
  src/main/java/depth/jeonsilog/domain/openApi/dto/API/ExhibitionListDTO.java
  src/main/java/depth/jeonsilog/domain/openApi/dto/API/PlaceDetailDTO.java
  src/main/java/depth/jeonsilog/domain/openApi/presentation/SaveController.java
  src/main/java/depth/jeonsilog/domain/place/application/PlaceService.java
  src/main/java/depth/jeonsilog/domain/place/converter/PlaceConverter.java
  src/main/java/depth/jeonsilog/domain/place/domain/Place.java
  src/main/java/depth/jeonsilog/domain/place/domain/repository/PlaceRepository.java
  src/main/java/depth/jeonsilog/domain/place/dto/PlaceRequestDto.java
  src/main/java/depth/jeonsilog/domain/place/dto/PlaceResponseDto.java
  src/main/java/depth/jeonsilog/domain/place/presentation/PlaceController.java
  src/main/java/depth/jeonsilog/domain/rating/application/RatingService.java
  src/main/java/depth/jeonsilog/domain/rating/converter/RatingConverter.java
  src/main/java/depth/jeonsilog/domain/rating/domain/Rating.java
  src/main/java/depth/jeonsilog/domain/rating/domain/repository/RatingRepository.java
  src/main/java/depth/jeonsilog/domain/rating/dto/RatingRequestDto.java
  src/main/java/depth/jeonsilog/domain/rating/dto/RatingResponseDto.java
  src/main/java/depth/jeonsilog/domain/rating/presentation/RatingController.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
  src/main/java/depth/jeonsilog/domain/review/domain/Review.java
  src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewRequestDto.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
  src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
Labels: :rocket: deployment

#26 ✨ [FEAT]: Reply API 개발
  src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
  src/main/java/depth/jeonsilog/domain/follow/presentation/FollowController.java
  src/main/java/depth/jeonsilog/domain/interest/presentation/InterestController.java
  src/main/java/depth/jeonsilog/domain/place/presentation/PlaceController.java
  src/main/java/depth/jeonsilog/domain/rating/presentation/RatingController.java
  src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
  src/main/java/depth/jeonsilog/domain/reply/converter/ReplyConverter.java
  src/main/java/depth/jeonsilog/domain/reply/domain/Reply.java
  src/main/java/depth/jeonsilog/domain/reply/domain/repository/ReplyRepository.java
  src/main/java/depth/jeonsilog/domain/reply/dto/ReplyRequestDto.java
  src/main/java/depth/jeonsilog/domain/reply/dto/ReplyResponseDto.java
  src/main/java/depth/jeonsilog/domain/reply/presentation/ReplyController.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
  src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#29 ✨ [FEAT]: 유저 프로필 사진 변경 API 개발
  src/main/java/depth/jeonsilog/domain/s3/application/S3Service.java
  src/main/java/depth/jeonsilog/domain/s3/application/S3Uploader.java
  src/main/java/depth/jeonsilog/domain/s3/presentation/S3Controller.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/domain/User.java
  src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
Labels: :sparkles: feature

#31 ✨ [FEAT]: Report API 개발
  src/main/java/depth/jeonsilog/domain/report/application/ReportService.java
  src/main/java/depth/jeonsilog/domain/report/converter/ReportConverter.java
  src/main/java/depth/jeonsilog/domain/report/domain/Report.java
  src/main/java/depth/jeonsilog/domain/report/domain/repository/ReportRepository.java
  src/main/java/depth/jeonsilog/domain/report/dto/ReportRequestDto.java
  src/main/java/depth/jeonsilog/domain/report/dto/ReportResponseDto.java
  src/main/java/depth/jeonsilog/domain/report/presentation/ReportController.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#32 ✨ [FEAT]: 포토캘린더 API 개발
  src/main/java/depth/jeonsilog/domain/calendar/application/CalendarService.java
  src/main/java/depth/jeonsilog/domain/calendar/converter/CalendarConverter.java
  src/main/java/depth/jeonsilog/domain/calendar/domain/Calendar.java
  src/main/java/depth/jeonsilog/domain/calendar/domain/repository/CalendarRepository.java
  src/main/java/depth/jeonsilog/domain/calendar/dto/CalendarRequestDto.java
  src/main/java/depth/jeonsilog/domain/calendar/dto/CalendarResponseDto.java
  src/main/java/depth/jeonsilog/domain/calendar/presentation/CalendarController.java
Labels: :sparkles: feature

#33 🚀 [FEAT]: 5차 배포
  .github/pull_request_template.md
  src/main/java/depth/jeonsilog/domain/calendar/application/CalendarService.java
  src/main/java/depth/jeonsilog/domain/calendar/converter/CalendarConverter.java
  src/main/java/depth/jeonsilog/domain/calendar/domain/Calendar.java
  src/main/java/depth/jeonsilog/domain/calendar/domain/repository/CalendarRepository.java
  src/main/java/depth/jeonsilog/domain/calendar/dto/CalendarRequestDto.java
  src/main/java/depth/jeonsilog/domain/calendar/dto/CalendarResponseDto.java
  src/main/java/depth/jeonsilog/domain/calendar/presentation/CalendarController.java
  src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
  src/main/java/depth/jeonsilog/domain/follow/presentation/FollowController.java
  src/main/java/depth/jeonsilog/domain/interest/presentation/InterestController.java
  src/main/java/depth/jeonsilog/domain/place/presentation/PlaceController.java
  src/main/java/depth/jeonsilog/domain/rating/presentation/RatingController.java
  src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
  src/main/java/depth/jeonsilog/domain/reply/converter/ReplyConverter.java
  src/main/java/depth/jeonsilog/domain/reply/domain/Reply.java
  src/main/java/depth/jeonsilog/domain/reply/domain/repository/ReplyRepository.java
  src/main/java/depth/jeonsilog/domain/reply/dto/ReplyRequestDto.java
  src/main/java/depth/jeonsilog/domain/reply/dto/ReplyResponseDto.java
  src/main/java/depth/jeonsilog/domain/reply/presentation/ReplyController.java
  src/main/java/depth/jeonsilog/domain/report/application/ReportService.java
  src/main/java/depth/jeonsilog/domain/report/converter/ReportConverter.java
  src/main/java/depth/jeonsilog/domain/report/domain/Report.java
  src/main/java/depth/jeonsilog/domain/report/domain/repository/ReportRepository.java
  src/main/java/depth/jeonsilog/domain/report/dto/ReportRequestDto.java
  src/main/java/depth/jeonsilog/domain/report/dto/ReportResponseDto.java
  src/main/java/depth/jeonsilog/domain/report/presentation/ReportController.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
  src/main/java/depth/jeonsilog/domain/s3/application/S3Service.java
  src/main/java/depth/jeonsilog/domain/s3/application/S3Uploader.java
  src/main/java/depth/jeonsilog/domain/s3/presentation/S3Controller.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/domain/User.java
  src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
Labels: :rocket: deployment
