Repository AndLetgo/2nd-Main-JeonsiLog-Server, pull requests merged in 2024-05, with the labels that each got.

#107 :sparkles: [FEAT]: 관심 전시회 중 기록하지 않은 전시회 대상으로 종료 임박 알림
  build.gradle
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmCreateService.java
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
  src/main/java/depth/jeonsilog/domain/follow/application/FollowService.java
  src/main/java/depth/jeonsilog/domain/interest/domain/repository/InterestQuerydslRepository.java
  src/main/java/depth/jeonsilog/domain/interest/domain/repository/InterestQuerydslRepositoryImpl.java
  src/main/java/depth/jeonsilog/domain/interest/domain/repository/InterestRepository.java
  src/main/java/depth/jeonsilog/domain/rating/application/RatingService.java
  src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/global/config/QueryDslConfig.java
Labels: :sparkles: feature

#109 [FEAT]: 홈 화면 전시회 카테고리별 전시회 목록 조회 추가
  src/main/generated/depth/jeonsilog/domain/alarm/domain/QAlarm.java
  src/main/generated/depth/jeonsilog/domain/auth/domain/QToken.java
  src/main/generated/depth/jeonsilog/domain/calendar/domain/QCalendar.java
  src/main/generated/depth/jeonsilog/domain/common/QBaseEntity.java
  src/main/generated/depth/jeonsilog/domain/exhibition/domain/QExhibition.java
  src/main/generated/depth/jeonsilog/domain/follow/domain/QFollow.java
  src/main/generated/depth/jeonsilog/domain/interest/domain/QInterest.java
  src/main/generated/depth/jeonsilog/domain/place/domain/QPlace.java
  src/main/generated/depth/jeonsilog/domain/rating/domain/QRating.java
  src/main/generated/depth/jeonsilog/domain/reply/domain/QReply.java
  src/main/generated/depth/jeonsilog/domain/report/domain/QReport.java
  src/main/generated/depth/jeonsilog/domain/review/domain/QReview.java
  src/main/generated/depth/jeonsilog/domain/stop/domain/QStop.java
  src/main/generated/depth/jeonsilog/domain/user/domain/QUser.java
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
  src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
Labels: :recycle: refactor, :sparkles: feature

#110 ✨ [FEAT]: Report 카운팅 기능 추가
  src/main/java/depth/jeonsilog/domain/report/application/ReportService.java
  src/main/java/depth/jeonsilog/domain/report/converter/ReportConverter.java
  src/main/java/depth/jeonsilog/domain/report/domain/Report.java
  src/main/java/depth/jeonsilog/domain/report/domain/ReportType.java
  src/main/java/depth/jeonsilog/domain/report/domain/repository/ReportQuerydslRepository.java
  src/main/java/depth/jeonsilog/domain/report/domain/repository/ReportQuerydslRepositoryImpl.java
  src/main/java/depth/jeonsilog/domain/report/domain/repository/ReportRepository.java
  src/main/java/depth/jeonsilog/domain/report/dto/ReportRequestDto.java
  src/main/java/depth/jeonsilog/domain/report/dto/ReportResponseDto.java
  src/main/java/depth/jeonsilog/domain/report/presentation/ReportController.java
  src/main/java/depth/jeonsilog/domain/stop/application/StopService.java
Labels: :recycle: refactor, :sparkles: feature

#111 [FEAT]: caption 컬럼 추가에 따른 로직 추가
  src/main/java/depth/jeonsilog/domain/calendar/application/CalendarService.java
  src/main/java/depth/jeonsilog/domain/calendar/converter/CalendarConverter.java
  src/main/java/depth/jeonsilog/domain/calendar/dto/CalendarRequestDto.java
  src/main/java/depth/jeonsilog/domain/calendar/dto/CalendarResponseDto.java
Labels: :recycle: refactor, :sparkles: feature

#113 [FEAT]: 매일 Operating Keyword 수정
  src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
  src/main/java/depth/jeonsilog/domain/openApi/application/ModifyService.java
Labels: :sparkles: feature

#114 🚀 [DEPLOY]: 유지보수 수정사항 반영
  build.gradle
  src/main/generated/depth/jeonsilog/domain/alarm/domain/QAlarm.java
  src/main/generated/depth/jeonsilog/domain/auth/domain/QToken.java
  src/main/generated/depth/jeonsilog/domain/calendar/domain/QCalendar.java
  src/main/generated/depth/jeonsilog/domain/common/QBaseEntity.java
  src/main/generated/depth/jeonsilog/domain/exhibition/domain/QExhibition.java
  src/main/generated/depth/jeonsilog/domain/follow/domain/QFollow.java
  src/main/generated/depth/jeonsilog/domain/interest/domain/QInterest.java
  src/main/generated/depth/jeonsilog/domain/place/domain/QPlace.java
  src/main/generated/depth/jeonsilog/domain/rating/domain/QRating.java
  src/main/generated/depth/jeonsilog/domain/reply/domain/QReply.java
  src/main/generated/depth/jeonsilog/domain/report/domain/QReport.java
  src/main/generated/depth/jeonsilog/domain/review/domain/QReview.java
  src/main/generated/depth/jeonsilog/domain/stop/domain/QStop.java
  src/main/generated/depth/jeonsilog/domain/user/domain/QUser.java
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmCreateService.java
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
  src/main/java/depth/jeonsilog/domain/auth/converter/AuthConverter.java
  src/main/java/depth/jeonsilog/domain/calendar/application/CalendarService.java
  src/main/java/depth/jeonsilog/domain/calendar/converter/CalendarConverter.java
  src/main/java/depth/jeonsilog/domain/calendar/dto/CalendarRequestDto.java
  src/main/java/depth/jeonsilog/domain/calendar/dto/CalendarResponseDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
  src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
  src/main/java/depth/jeonsilog/domain/follow/application/FollowService.java
  src/main/java/depth/jeonsilog/domain/interest/domain/repository/InterestQuerydslRepository.java
  src/main/java/depth/jeonsilog/domain/interest/domain/repository/InterestQuerydslRepositoryImpl.java
  src/main/java/depth/jeonsilog/domain/interest/domain/repository/InterestRepository.java
  src/main/java/depth/jeonsilog/domain/openApi/application/ModifyService.java
  src/main/java/depth/jeonsilog/domain/rating/application/RatingService.java
  src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
  src/main/java/depth/jeonsilog/domain/report/application/ReportService.java
  src/main/java/depth/jeonsilog/domain/report/converter/ReportConverter.java
  src/main/java/depth/jeonsilog/domain/report/domain/Report.java
  src/main/java/depth/jeonsilog/domain/report/domain/ReportType.java
  src/main/java/depth/jeonsilog/domain/report/domain/repository/ReportQuerydslRepository.java
  src/main/java/depth/jeonsilog/domain/report/domain/repository/ReportQuerydslRepositoryImpl.java
  src/main/java/depth/jeonsilog/domain/report/domain/repository/ReportRepository.java
  src/main/java/depth/jeonsilog/domain/report/dto/ReportRequestDto.java
  src/main/java/depth/jeonsilog/domain/report/dto/ReportResponseDto.java
  src/main/java/depth/jeonsilog/domain/report/presentation/ReportController.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/stop/application/StopService.java
  src/main/java/depth/jeonsilog/domain/stop/domain/Stop.java
  src/main/java/depth/jeonsilog/domain/stop/domain/repository/StopRepository.java
  src/main/java/depth/jeonsilog/domain/stop/dto/StopRequestDto.java
  src/main/java/depth/jeonsilog/domain/stop/dto/StopResponseDto.java
  src/main/java/depth/jeonsilog/domain/stop/presentation/StopController.java
  src/main/java/depth/jeonsilog/domain/user/domain/User.java
  src/main/java/depth/jeonsilog/global/config/QueryDslConfig.java
Labels: :rocket: deployment

#117 :sparkles: [FEAT]: 유저 정지 조회 response에 최초 여부 추가
  src/main/java/depth/jeonsilog/domain/stop/application/StopService.java
  src/main/java/depth/jeonsilog/domain/stop/dto/StopResponseDto.java
Labels: :sparkles: feature, ✍ chore

#118 :sparkles: [FEAT]: 같은 사용자가 여러 번 신고했을 때 한 번으로 처리
  src/main/java/depth/jeonsilog/domain/report/application/ReportService.java
  src/main/java/depth/jeonsilog/domain/report/domain/repository/ReportRepository.java
  src/main/java/depth/jeonsilog/domain/report/presentation/ReportController.java
Labels: :sparkles: feature

#120 ✨ [FEAT]: 유저 조회 시 응답 값 추가
  src/main/java/depth/jeonsilog/domain/reply/converter/ReplyConverter.java
  src/main/java/depth/jeonsilog/domain/reply/dto/ReplyResponseDto.java
  src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
  src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
Labels: :sparkles: feature

#121 🚀 [DEPLOY]: 추가 수정사항 반영 - 유저레벨, 정지, 신고
  src/main/java/depth/jeonsilog/domain/reply/converter/ReplyConverter.java
  src/main/java/depth/jeonsilog/domain/reply/dto/ReplyResponseDto.java
  src/main/java/depth/jeonsilog/domain/report/application/ReportService.java
  src/main/java/depth/jeonsilog/domain/report/domain/repository/ReportRepository.java
  src/main/java/depth/jeonsilog/domain/report/presentation/ReportController.java
  src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
  src/main/java/depth/jeonsilog/domain/stop/application/StopService.java
  src/main/java/depth/jeonsilog/domain/stop/dto/StopResponseDto.java
  src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
Labels: :rocket: deployment

#123 :sparkles: [FEAT]: 감상평 조회에 exhibitionID 추가
  src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
Labels: :sparkles: feature

#124 🚀 [DEPLOY]: 감상평 조회에 exhibitionId 추가
  src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
Labels: :rocket: deployment

#126 [FIX]: 새로 시작된 전시 조회 시 ON_DISPLAY만
  src/main/generated/depth/jeonsilog/domain/report/domain/QReport.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
Labels: :bug: bug

#127 🚀 [DEPLOY]: 새로 시작된 전시에 ON_DISPLAY만
  src/main/generated/depth/jeonsilog/domain/report/domain/QReport.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
Labels: :rocket: deployment

#129 [FIX]: 전시회 랜덤 로직 수정
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
  src/main/resources/application.yml
Labels: :bug: bug, :ambulance: hotfix

#130 [DEPLOY] : 전시회 랜덤 로직 수정 배포
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
Labels: :rocket: deployment
