Repository AndLetgo/2nd-Main-JeonsiLog-Server, pull requests merged in 2024-01, with the labels that each got.

#37 🐛 [FIX]: 확인된 API 오류 수정
  .github/PR_TEMPLATE/pull_request_template.md
  README.md
  src/main/java/depth/jeonsilog/domain/auth/application/AuthService.java
  src/main/java/depth/jeonsilog/domain/calendar/application/CalendarService.java
  src/main/java/depth/jeonsilog/domain/calendar/domain/Calendar.java
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/exhibition/converter/ExhibitionConverter.java
  src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionResponseDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
  src/main/java/depth/jeonsilog/domain/follow/application/FollowService.java
  src/main/java/depth/jeonsilog/domain/rating/application/RatingService.java
  src/main/java/depth/jeonsilog/domain/s3/application/S3Uploader.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/domain/User.java
  src/main/java/depth/jeonsilog/domain/user/domain/repository/UserRepository.java
Labels: :bug: bug

#38 ✨ [FEAT]: 알림 조회 API 개발
  src/main/java/depth/jeonsilog/JeonsiLogServerApplication.java
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
  src/main/java/depth/jeonsilog/domain/alarm/converter/AlarmConverter.java
  src/main/java/depth/jeonsilog/domain/alarm/domain/Alarm.java
  src/main/java/depth/jeonsilog/domain/alarm/domain/AlarmType.java
  src/main/java/depth/jeonsilog/domain/alarm/domain/repository/AlarmRepository.java
  src/main/java/depth/jeonsilog/domain/alarm/dto/AlarmResponseDto.java
  src/main/java/depth/jeonsilog/domain/alarm/presentation/AlarmController.java
  src/main/java/depth/jeonsilog/domain/follow/application/FollowService.java
  src/main/java/depth/jeonsilog/domain/interest/domain/repository/InterestRepository.java
  src/main/java/depth/jeonsilog/domain/rating/application/RatingService.java
  src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
Labels: :sparkles: feature

#39 🚀 [FEAT]: 6차 배포
  src/main/java/depth/jeonsilog/JeonsiLogServerApplication.java
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
  src/main/java/depth/jeonsilog/domain/alarm/converter/AlarmConverter.java
  src/main/java/depth/jeonsilog/domain/alarm/domain/Alarm.java
  src/main/java/depth/jeonsilog/domain/alarm/domain/AlarmType.java
  src/main/java/depth/jeonsilog/domain/alarm/domain/repository/AlarmRepository.java
  src/main/java/depth/jeonsilog/domain/alarm/dto/AlarmResponseDto.java
  src/main/java/depth/jeonsilog/domain/alarm/presentation/AlarmController.java
  src/main/java/depth/jeonsilog/domain/auth/application/AuthService.java
  src/main/java/depth/jeonsilog/domain/calendar/application/CalendarService.java
  src/main/java/depth/jeonsilog/domain/calendar/domain/Calendar.java
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/exhibition/converter/ExhibitionConverter.java
  src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionResponseDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
  src/main/java/depth/jeonsilog/domain/follow/application/FollowService.java
  src/main/java/depth/jeonsilog/domain/interest/domain/repository/InterestRepository.java
  src/main/java/depth/jeonsilog/domain/rating/application/RatingService.java
  src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/s3/application/S3Uploader.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/domain/User.java
  src/main/java/depth/jeonsilog/domain/user/domain/repository/UserRepository.java
Labels: :rocket: deployment

#43 🐛 [FIX]: 대면 회의 후 API 수정 사항 반영
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
  src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionRequestDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
  src/main/java/depth/jeonsilog/domain/place/domain/Place.java
  src/main/java/depth/jeonsilog/domain/place/dto/PlaceRequestDto.java
  src/main/java/depth/jeonsilog/domain/rating/domain/Rating.java
  src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
  src/main/java/depth/jeonsilog/domain/reply/domain/repository/ReplyRepository.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/domain/User.java
Labels: :bug: bug

#45 ✨ [FEAT]: Exhibition 추가 API 개발
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/exhibition/converter/ExhibitionConverter.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
  src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionRequestDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionResponseDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
Labels: :sparkles: feature

#48 🐛 [FIX]: place 검색 조건 수정 및 유저 탈퇴 시 s3에서 프로필 이미지 삭제
  src/main/java/depth/jeonsilog/domain/place/application/PlaceService.java
  src/main/java/depth/jeonsilog/domain/place/domain/repository/PlaceRepository.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
Labels: :bug: bug

#49 ✨ [FEAT]: User, Alarm, Review API 개발 (대면 회의 후)
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
  src/main/java/depth/jeonsilog/domain/alarm/converter/AlarmConverter.java
  src/main/java/depth/jeonsilog/domain/alarm/domain/Alarm.java
  src/main/java/depth/jeonsilog/domain/alarm/dto/AlarmResponseDto.java
  src/main/java/depth/jeonsilog/domain/alarm/presentation/AlarmController.java
  src/main/java/depth/jeonsilog/domain/report/converter/ReportConverter.java
  src/main/java/depth/jeonsilog/domain/report/domain/Report.java
  src/main/java/depth/jeonsilog/domain/report/dto/ReportResponseDto.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
  src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
  src/main/java/depth/jeonsilog/domain/user/domain/User.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
  src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
Labels: :sparkles: feature

#51 ✨ [FEAT]: Auth, Follow, Review, Place API response 추가 (대면 회의 후)
  .gitignore
  src/main/java/depth/jeonsilog/domain/auth/application/AuthService.java
  src/main/java/depth/jeonsilog/domain/auth/dto/AuthResponseDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/converter/ExhibitionConverter.java
  src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionResponseDto.java
  src/main/java/depth/jeonsilog/domain/follow/converter/FollowConverter.java
  src/main/java/depth/jeonsilog/domain/follow/dto/FollowResponseDto.java
  src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
  src/main/resources/forbidden-words.txt
Labels: :sparkles: feature

#52 ✨ [FEAT]: 데이터 정리 로직 개발
  src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
  src/main/java/depth/jeonsilog/domain/openApi/application/ModifyService.java
  src/main/java/depth/jeonsilog/domain/openApi/application/SaveService.java
  src/main/java/depth/jeonsilog/domain/openApi/presentation/ModifyController.java
  src/main/java/depth/jeonsilog/domain/place/domain/Place.java
Labels: :sparkles: feature

#55 🚀 7차 배포
  .github/workflows/deploy.yml
  .gitignore
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
  src/main/java/depth/jeonsilog/domain/alarm/converter/AlarmConverter.java
  src/main/java/depth/jeonsilog/domain/alarm/domain/Alarm.java
  src/main/java/depth/jeonsilog/domain/alarm/dto/AlarmResponseDto.java
  src/main/java/depth/jeonsilog/domain/alarm/presentation/AlarmController.java
  src/main/java/depth/jeonsilog/domain/auth/application/AuthService.java
  src/main/java/depth/jeonsilog/domain/auth/dto/AuthResponseDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/exhibition/converter/ExhibitionConverter.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
  src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionRequestDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionResponseDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
  src/main/java/depth/jeonsilog/domain/follow/converter/FollowConverter.java
  src/main/java/depth/jeonsilog/domain/follow/dto/FollowResponseDto.java
  src/main/java/depth/jeonsilog/domain/openApi/application/ModifyService.java
  src/main/java/depth/jeonsilog/domain/openApi/application/SaveService.java
  src/main/java/depth/jeonsilog/domain/openApi/presentation/ModifyController.java
  src/main/java/depth/jeonsilog/domain/place/application/PlaceService.java
  src/main/java/depth/jeonsilog/domain/place/domain/Place.java
  src/main/java/depth/jeonsilog/domain/place/domain/repository/PlaceRepository.java
  src/main/java/depth/jeonsilog/domain/place/dto/PlaceRequestDto.java
  src/main/java/depth/jeonsilog/domain/rating/domain/Rating.java
  src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
  src/main/java/depth/jeonsilog/domain/reply/domain/repository/ReplyRepository.java
  src/main/java/depth/jeonsilog/domain/report/converter/ReportConverter.java
  src/main/java/depth/jeonsilog/domain/report/domain/Report.java
  src/main/java/depth/jeonsilog/domain/report/dto/ReportResponseDto.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
  src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
  src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
  src/main/java/depth/jeonsilog/domain/user/domain/User.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
  src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
Labels: :rocket: deployment

#56 ✨ [FEAT]: 전시회 갱신(추가 저장) 로직 개발
  src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
  src/main/java/depth/jeonsilog/domain/openApi/application/AddService.java
  src/main/java/depth/jeonsilog/domain/openApi/application/SaveService.java
  src/main/java/depth/jeonsilog/domain/openApi/presentation/AddController.java
  src/main/java/depth/jeonsilog/domain/place/converter/PlaceConverter.java
  src/main/java/depth/jeonsilog/domain/place/domain/ClosedDays.java
  src/main/java/depth/jeonsilog/domain/place/domain/Place.java
  src/main/java/depth/jeonsilog/domain/place/dto/PlaceRequestDto.java
  src/main/java/depth/jeonsilog/domain/place/dto/PlaceResponseDto.java
Labels: :sparkles: feature

#57 ✨ [FEAT]: 목록 조회 API 페이징 처리
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
  src/main/java/depth/jeonsilog/domain/alarm/domain/repository/AlarmRepository.java
  src/main/java/depth/jeonsilog/domain/alarm/presentation/AlarmController.java
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
  src/main/java/depth/jeonsilog/domain/follow/application/FollowService.java
  src/main/java/depth/jeonsilog/domain/follow/domain/repository/FollowRepository.java
  src/main/java/depth/jeonsilog/domain/follow/presentation/FollowController.java
  src/main/java/depth/jeonsilog/domain/interest/application/InterestService.java
  src/main/java/depth/jeonsilog/domain/interest/domain/repository/InterestRepository.java
  src/main/java/depth/jeonsilog/domain/interest/presentation/InterestController.java
  src/main/java/depth/jeonsilog/domain/place/application/PlaceService.java
  src/main/java/depth/jeonsilog/domain/rating/application/RatingService.java
  src/main/java/depth/jeonsilog/domain/rating/domain/repository/RatingRepository.java
  src/main/java/depth/jeonsilog/domain/rating/presentation/RatingController.java
  src/main/java/depth/jeonsilog/domain/report/application/ReportService.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
  src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/domain/repository/UserRepository.java
  src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
Labels: :sparkles: feature

#58 🚀 [DEPLOY]: 8차 배포
  .github/workflows/deploy.yml
Labels: :rocket: deployment

#62 🐛 [FIX]: 기능 개발 완료 후 발견되는 문제 수정
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
  src/main/java/depth/jeonsilog/domain/alarm/converter/AlarmConverter.java
  src/main/java/depth/jeonsilog/domain/alarm/domain/repository/AlarmRepository.java
  src/main/java/depth/jeonsilog/domain/alarm/dto/AlarmResponseDto.java
  src/main/java/depth/jeonsilog/domain/alarm/presentation/AlarmController.java
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/exhibition/converter/ExhibitionConverter.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
  src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionResponseDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
  src/main/java/depth/jeonsilog/domain/follow/application/FollowService.java
  src/main/java/depth/jeonsilog/domain/follow/converter/FollowConverter.java
  src/main/java/depth/jeonsilog/domain/follow/domain/repository/FollowRepository.java
  src/main/java/depth/jeonsilog/domain/follow/dto/FollowResponseDto.java
  src/main/java/depth/jeonsilog/domain/follow/presentation/FollowController.java
  src/main/java/depth/jeonsilog/domain/interest/application/InterestService.java
  src/main/java/depth/jeonsilog/domain/interest/converter/InterestConverter.java
  src/main/java/depth/jeonsilog/domain/interest/domain/repository/InterestRepository.java
  src/main/java/depth/jeonsilog/domain/interest/dto/InterestResponseDto.java
  src/main/java/depth/jeonsilog/domain/interest/presentation/InterestController.java
  src/main/java/depth/jeonsilog/domain/place/application/PlaceService.java
  src/main/java/depth/jeonsilog/domain/place/converter/PlaceConverter.java
  src/main/java/depth/jeonsilog/domain/place/domain/repository/PlaceRepository.java
  src/main/java/depth/jeonsilog/domain/place/dto/PlaceResponseDto.java
  src/main/java/depth/jeonsilog/domain/place/presentation/PlaceController.java
  src/main/java/depth/jeonsilog/domain/rating/application/RatingService.java
  src/main/java/depth/jeonsilog/domain/rating/converter/RatingConverter.java
  src/main/java/depth/jeonsilog/domain/rating/dto/RatingResponseDto.java
  src/main/java/depth/jeonsilog/domain/rating/presentation/RatingController.java
  src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
  src/main/java/depth/jeonsilog/domain/reply/converter/ReplyConverter.java
  src/main/java/depth/jeonsilog/domain/reply/domain/repository/ReplyRepository.java
  src/main/java/depth/jeonsilog/domain/reply/dto/ReplyResponseDto.java
  src/main/java/depth/jeonsilog/domain/reply/presentation/ReplyController.java
  src/main/java/depth/jeonsilog/domain/report/application/ReportService.java
  src/main/java/depth/jeonsilog/domain/report/converter/ReportConverter.java
  src/main/java/depth/jeonsilog/domain/report/domain/repository/ReportRepository.java
  src/main/java/depth/jeonsilog/domain/report/dto/ReportResponseDto.java
  src/main/java/depth/jeonsilog/domain/report/presentation/ReportController.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
  src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
  src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
  src/main/java/depth/jeonsilog/domain/user/domain/repository/UserRepository.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
  src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
Labels: :bug: bug

#64 🚀 [DEPLOY]: 9차 배포
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
  src/main/java/depth/jeonsilog/domain/alarm/converter/AlarmConverter.java
  src/main/java/depth/jeonsilog/domain/alarm/domain/repository/AlarmRepository.java
  src/main/java/depth/jeonsilog/domain/alarm/dto/AlarmResponseDto.java
  src/main/java/depth/jeonsilog/domain/alarm/presentation/AlarmController.java
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/exhibition/converter/ExhibitionConverter.java
  src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
  src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionResponseDto.java
  src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
  src/main/java/depth/jeonsilog/domain/follow/application/FollowService.java
  src/main/java/depth/jeonsilog/domain/follow/converter/FollowConverter.java
  src/main/java/depth/jeonsilog/domain/follow/domain/repository/FollowRepository.java
  src/main/java/depth/jeonsilog/domain/follow/dto/FollowResponseDto.java
  src/main/java/depth/jeonsilog/domain/follow/presentation/FollowController.java
  src/main/java/depth/jeonsilog/domain/interest/application/InterestService.java
  src/main/java/depth/jeonsilog/domain/interest/converter/InterestConverter.java
  src/main/java/depth/jeonsilog/domain/interest/domain/repository/InterestRepository.java
  src/main/java/depth/jeonsilog/domain/interest/dto/InterestResponseDto.java
  src/main/java/depth/jeonsilog/domain/interest/presentation/InterestController.java
  src/main/java/depth/jeonsilog/domain/place/application/PlaceService.java
  src/main/java/depth/jeonsilog/domain/place/converter/PlaceConverter.java
  src/main/java/depth/jeonsilog/domain/place/domain/repository/PlaceRepository.java
  src/main/java/depth/jeonsilog/domain/place/dto/PlaceResponseDto.java
  src/main/java/depth/jeonsilog/domain/place/presentation/PlaceController.java
  src/main/java/depth/jeonsilog/domain/rating/application/RatingService.java
  src/main/java/depth/jeonsilog/domain/rating/converter/RatingConverter.java
  src/main/java/depth/jeonsilog/domain/rating/dto/RatingResponseDto.java
  src/main/java/depth/jeonsilog/domain/rating/presentation/RatingController.java
  src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
  src/main/java/depth/jeonsilog/domain/reply/converter/ReplyConverter.java
  src/main/java/depth/jeonsilog/domain/reply/domain/repository/ReplyRepository.java
  src/main/java/depth/jeonsilog/domain/reply/dto/ReplyResponseDto.java
  src/main/java/depth/jeonsilog/domain/reply/presentation/ReplyController.java
  src/main/java/depth/jeonsilog/domain/report/application/ReportService.java
  src/main/java/depth/jeonsilog/domain/report/converter/ReportConverter.java
  src/main/java/depth/jeonsilog/domain/report/domain/repository/ReportRepository.java
  src/main/java/depth/jeonsilog/domain/report/dto/ReportResponseDto.java
  src/main/java/depth/jeonsilog/domain/report/presentation/ReportController.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
  src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
  src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
  src/main/java/depth/jeonsilog/domain/user/domain/repository/UserRepository.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
  src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
Labels: :rocket: deployment

#66 🚀 [DEPLOY]: 10차 배포
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
  src/main/java/depth/jeonsilog/domain/place/application/PlaceService.java
  src/main/java/depth/jeonsilog/domain/place/converter/PlaceConverter.java
  src/main/java/depth/jeonsilog/domain/place/domain/repository/PlaceRepository.java
  src/main/java/depth/jeonsilog/domain/place/dto/PlaceResponseDto.java
  src/main/java/depth/jeonsilog/domain/place/presentation/PlaceController.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
Labels: :rocket: deployment

#69 🐛 [FIX]: 회원탈퇴 로직 수정
  src/main/java/depth/jeonsilog/domain/reply/domain/repository/ReplyRepository.java
  src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
Labels: :bug: bug

#70 ✨ [FEAT]: FCM을 활용한 푸시 알림 구현, User 엔티티 컬럼 변경
  .gitignore
  build.gradle
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
  src/main/java/depth/jeonsilog/domain/auth/converter/AuthConverter.java
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/fcm/application/FcmService.java
  src/main/java/depth/jeonsilog/domain/follow/application/FollowService.java
  src/main/java/depth/jeonsilog/domain/follow/presentation/FollowController.java
  src/main/java/depth/jeonsilog/domain/rating/application/RatingService.java
  src/main/java/depth/jeonsilog/domain/rating/presentation/RatingController.java
  src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
  src/main/java/depth/jeonsilog/domain/reply/presentation/ReplyController.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
  src/main/java/depth/jeonsilog/domain/user/domain/User.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserRequestDto.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
  src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
  src/main/java/depth/jeonsilog/global/config/FcmConfig.java
Labels: :sparkles: feature

#71 🚀 [DEPLOY]: 11차 배포
  .github/workflows/deploy.yml
  .gitignore
  build.gradle
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
  src/main/java/depth/jeonsilog/domain/auth/converter/AuthConverter.java
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
  src/main/java/depth/jeonsilog/domain/fcm/application/FcmService.java
  src/main/java/depth/jeonsilog/domain/follow/application/FollowService.java
  src/main/java/depth/jeonsilog/domain/follow/presentation/FollowController.java
  src/main/java/depth/jeonsilog/domain/rating/application/RatingService.java
  src/main/java/depth/jeonsilog/domain/rating/presentation/RatingController.java
  src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
  src/main/java/depth/jeonsilog/domain/reply/domain/repository/ReplyRepository.java
  src/main/java/depth/jeonsilog/domain/reply/presentation/ReplyController.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
  src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
  src/main/java/depth/jeonsilog/domain/user/domain/User.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserRequestDto.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
  src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
  src/main/java/depth/jeonsilog/global/config/FcmConfig.java
Labels: :rocket: deployment

#72 🐛 [FIX]: 유저 및 전시회 image null, not null 처리
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
Labels: :bug: bug

#74 ✨ [FEAT]: 추가 API 개발 및 수정 사항 반영
  src/main/java/depth/jeonsilog/domain/fcm/application/FcmService.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
  src/main/java/depth/jeonsilog/domain/review/domain/Review.java
  src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewRequestDto.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
  src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
  src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
Labels: :bug: bug, :sparkles: feature, :rocket: deployment

#75 🚀 [DEPLOY]: 12차 배포
  src/main/java/depth/jeonsilog/domain/fcm/application/FcmService.java
  src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
  src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
  src/main/java/depth/jeonsilog/domain/review/domain/Review.java
  src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewRequestDto.java
  src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
  src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
  src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
  src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
Labels: :rocket: deployment

#76 🐛 [FIX]: 추가적인 수정 사항 반영
  src/main/java/depth/jeonsilog/domain/openApi/application/AddService.java
  src/main/java/depth/jeonsilog/domain/openApi/application/SaveService.java
  src/main/java/depth/jeonsilog/domain/openApi/presentation/AddController.java
  src/main/java/depth/jeonsilog/domain/openApi/presentation/ModifyController.java
  src/main/java/depth/jeonsilog/domain/openApi/presentation/SaveController.java
  src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
  src/main/resources/application-swagger.yml
Labels: :bug: bug, ✍ chore

#78 ♻️[REFACTOR]: 푸시 알림 내용, 코드 리팩토링
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
  src/main/java/depth/jeonsilog/domain/fcm/application/FcmService.java
Labels: :recycle: refactor, ✍ chore

#79 🚀 [DEPLOY]: 13차 배포
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
  src/main/java/depth/jeonsilog/domain/fcm/application/FcmService.java
  src/main/java/depth/jeonsilog/domain/openApi/application/AddService.java
  src/main/java/depth/jeonsilog/domain/openApi/application/SaveService.java
  src/main/java/depth/jeonsilog/domain/openApi/presentation/AddController.java
  src/main/java/depth/jeonsilog/domain/openApi/presentation/ModifyController.java
  src/main/java/depth/jeonsilog/domain/openApi/presentation/SaveController.java
  src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
  src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
  src/main/resources/application-swagger.yml
Labels: :rocket: deployment

#80 🐛 [FIX]: Permission denied 해결
  appspec.yml
Labels: :bug: bug

#81 🚀 [DEPLOY]: Permission denied 해결 배포
  appspec.yml
Labels: :rocket: deployment

#82 🐛 [FIX]: Place null 수정 시 일괄 수정 문제 해결
  src/main/java/depth/jeonsilog/domain/openApi/application/AddService.java
  src/main/java/depth/jeonsilog/domain/openApi/application/SaveService.java
  src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
  src/main/java/depth/jeonsilog/domain/reply/converter/ReplyConverter.java
  src/main/java/depth/jeonsilog/domain/reply/domain/repository/ReplyRepository.java
  src/main/java/depth/jeonsilog/domain/reply/dto/ReplyResponseDto.java
  src/main/java/depth/jeonsilog/domain/reply/presentation/ReplyController.java
  src/main/java/depth/jeonsilog/domain/report/application/ReportService.java
  src/main/java/depth/jeonsilog/domain/report/converter/ReportConverter.java
  src/main/java/depth/jeonsilog/domain/report/dto/ReportResponseDto.java
  src/main/java/depth/jeonsilog/domain/report/presentation/ReportController.java
  src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
Labels: :bug: bug, :recycle: refactor, :sparkles: feature, ✍ chore

#84 🐛[FIX]: 나의 감상평에 내가 댓글 작성 시 알림 생성되지 않도록 수정
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
Labels: :bug: bug

#85 🚀 [DEPLOY]: QA 및 추가 수정 사항 반영 배포
  src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
  src/main/java/depth/jeonsilog/domain/openApi/application/AddService.java
  src/main/java/depth/jeonsilog/domain/openApi/application/SaveService.java
  src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
  src/main/java/depth/jeonsilog/domain/reply/converter/ReplyConverter.java
  src/main/java/depth/jeonsilog/domain/reply/domain/repository/ReplyRepository.java
  src/main/java/depth/jeonsilog/domain/reply/dto/ReplyResponseDto.java
  src/main/java/depth/jeonsilog/domain/reply/presentation/ReplyController.java
  src/main/java/depth/jeonsilog/domain/report/application/ReportService.java
  src/main/java/depth/jeonsilog/domain/report/converter/ReportConverter.java
  src/main/java/depth/jeonsilog/domain/report/dto/ReportResponseDto.java
  src/main/java/depth/jeonsilog/domain/report/presentation/ReportController.java
  src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
Labels: :rocket: deployment

#86 🐛 [FIX]: 회원 탈퇴 로직 수정
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
Labels: :bug: bug

#87 🚀 [DEPLOY]: 틈새 배포
  src/main/java/depth/jeonsilog/domain/user/application/UserService.java
Labels: :rocket: deployment

#90 🚑 [HOTFIX]: 전시회 랜덤 조회 로직 수정
  src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
Labels: :rocket: deployment
